#!/usr/bin/env python3
"""Insert or refresh lore-eden's managed hook block in a workspace lefthook.yml.

Splitting this out of the shell wrapper is not ceremony: the edit has to find the
`pre-commit:` section, find its `commands:` map, match that map's indentation, and
replace an existing managed block without disturbing anything around it. That is
text surgery on someone else's config file, and doing it in awk is how you corrupt
a repo you do not own.

Stdlib only — this runs against arbitrary workspaces, which may have no venv.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import List, NamedTuple, Optional, Tuple

BEGIN_MARKER = "# >>> lore-eden gate guardrails (managed) >>>"
END_MARKER = "# <<< lore-eden gate guardrails (managed) <<<"

#: Markers written by loregarden's predecessor of this installer. Recognised so
#: that installing over a repo which still carries the old block replaces it
#: rather than stacking a second copy beside it — two blocks would run every
#: gate twice, which is the exact defect this library exists to remove.
LEGACY_MARKERS = (
    (
        "# >>> loregarden organization guardrails (managed) >>>",
        "# <<< loregarden organization guardrails (managed) <<<",
    ),
)

#: Namespace for the command names this block writes. Namespaced deliberately: a
#: workspace may already have a `py-organization` of its own, and a second entry
#: under the same key in the same map is a duplicate YAML key — the parser either
#: errors or silently keeps one, quietly disabling the workspace's existing gate.
#: The prefix also makes provenance obvious in lefthook's output.
COMMAND_PREFIX = "lore-eden"


class ManagedGate(NamedTuple):
    """One command the managed block writes."""

    name: str
    title: str
    runner: str
    script: str
    glob: str


#: `**/*.py` matches nested files only — lefthook skipped a root-level `foo.py`
#: outright, reporting "no files for inspection", which reads exactly like a pass.
#: The alternation covers both depths. Verified against lefthook v2.1.10.
PY_GLOB = "{*.py,**/*.py}"
TS_GLOB = "{*.ts,*.tsx,**/*.ts,**/*.tsx}"

#: Every gate whose rules hold in any repo. The two the predecessor never
#: installed — git-subprocess routing and defensive normalization — are here:
#: both enforce universal rules, and leaving them out meant they only ever ran
#: in the repo they were written in.
MANAGED_GATES: Tuple[ManagedGate, ...] = (
    ManagedGate(
        f"{COMMAND_PREFIX}-py-organization",
        "Python organization guardrails",
        "python3",
        "py_organization_check.py",
        PY_GLOB,
    ),
    ManagedGate(
        f"{COMMAND_PREFIX}-py-silent-except",
        "Python silently-caught exceptions",
        "python3",
        "py_silent_except_check.py",
        PY_GLOB,
    ),
    ManagedGate(
        f"{COMMAND_PREFIX}-py-git-subprocess",
        "Python git subprocess routing",
        "python3",
        "py_git_subprocess_check.py",
        PY_GLOB,
    ),
    ManagedGate(
        f"{COMMAND_PREFIX}-py-defensive-normalization",
        "Python defensive normalization",
        "python3",
        "py_defensive_normalization_check.py",
        PY_GLOB,
    ),
    ManagedGate(
        f"{COMMAND_PREFIX}-ts-organization",
        "TypeScript organization guardrails",
        "node",
        "ts_organization_check.cjs",
        TS_GLOB,
    ),
)

MANAGED_COMMAND_NAMES = tuple(gate.name for gate in MANAGED_GATES)


def render_block(gates_root: Path, indent: str) -> List[str]:
    """The managed block, pointing at the gate scripts in ``gates_root``."""
    body = [
        BEGIN_MARKER,
        "# Generated by lore-eden's install-workspace-hooks.sh — do not edit by",
        "# hand; re-run that script to refresh. The rules live in lore-eden.",
    ]
    for gate in MANAGED_GATES:
        body.extend(
            [
                f"{gate.name}:",
                f"  name: {gate.title} (lore-eden)",
                "  priority: 1",
                f'  glob: "{gate.glob}"',
                f"  run: {gate.runner} {gates_root / gate.script} {{staged_files}}",
            ]
        )
    body.append(END_MARKER)
    return [f"{indent}{line}" if line.strip() else line for line in body]


def colliding_commands(lines: List[str]) -> List[str]:
    """Managed names already defined outside the managed block.

    Namespacing makes this near-impossible, but writing a duplicate key into
    someone else's config is bad enough to be worth refusing rather than
    discovering later as a gate that stopped running.
    """
    defined = {
        line.strip().rstrip(":")
        for line in lines
        if line.strip().endswith(":") and not line.strip().startswith("#")
    }
    return [name for name in MANAGED_COMMAND_NAMES if name in defined]


def find_commands_map(lines: List[str]) -> Optional[Tuple[int, str]]:
    """Return (line index after `commands:`, indent for its entries).

    The entry indent is read from the first existing entry rather than assumed,
    so this matches whatever style the target repo already uses.
    """
    try:
        start = next(i for i, line in enumerate(lines) if line.startswith("pre-commit:"))
    except StopIteration:
        return None
    commands = None
    for i in range(start + 1, len(lines)):
        line = lines[i]
        if line and not line[0].isspace():
            break  # next top-level section; pre-commit had no commands map
        if line.strip() == "commands:":
            commands = i
            break
    if commands is None:
        return None

    map_indent = len(lines[commands]) - len(lines[commands].lstrip())
    entry_indent = " " * (map_indent + 2)
    for i in range(commands + 1, len(lines)):
        line = lines[i]
        if not line.strip():
            continue
        indent = len(line) - len(line.lstrip())
        if indent <= map_indent:
            break
        entry_indent = " " * indent
        break
    return commands, entry_indent


def strip_managed_block(lines: List[str]) -> Tuple[List[str], List[str]]:
    """Split out the existing managed block, if any. Returns (rest, block).

    Legacy markers count as "the managed block" too, so installing over a repo
    that still carries the predecessor's block replaces it instead of leaving
    both in place — two blocks means every gate runs twice.
    """
    marker_pairs = ((BEGIN_MARKER, END_MARKER), *LEGACY_MARKERS)
    begins = {begin for begin, _ in marker_pairs}
    ends = {end for _, end in marker_pairs}

    out: List[str] = []
    block: List[str] = []
    inside = False
    for line in lines:
        if line.strip() in begins:
            inside = True
            block.append(line)
            continue
        if line.strip() in ends:
            inside = False
            block.append(line)
            continue
        (block if inside else out).append(line)
    return out, block


def end_of_commands_map(lines: List[str], commands_index: int, entry_indent: str) -> int:
    """First line after the commands map ends."""
    map_indent = len(lines[commands_index]) - len(lines[commands_index].lstrip())
    end = len(lines)
    for i in range(commands_index + 1, len(lines)):
        line = lines[i]
        if not line.strip():
            continue
        indent = len(line) - len(line.lstrip())
        if indent <= map_indent:
            end = i
            break
    # Do not swallow blank lines that separate sections.
    while end > commands_index + 1 and not lines[end - 1].strip():
        end -= 1
    return end


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", required=True)
    parser.add_argument(
        "--gates-root",
        required=True,
        help="Directory holding the gate scripts the managed block will invoke.",
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    config = Path(args.config)
    original = config.read_text(encoding="utf-8").splitlines()
    rest, existing = strip_managed_block(original)

    located = find_commands_map(rest)
    if located is None:
        print(f"skip: {config} has no pre-commit commands map", file=sys.stderr)
        return 1
    collisions = colliding_commands(rest)
    if collisions:
        print(
            f"skip: {config.parent} already defines {', '.join(collisions)} outside the "
            "managed block; rename or remove it first rather than have two entries "
            "under one key",
            file=sys.stderr,
        )
        return 1

    commands_index, entry_indent = located
    block = render_block(Path(args.gates_root), entry_indent)

    if existing == block:
        print(f"ok: {config.parent} already current")
        return 0
    if args.check:
        state = "outdated" if existing else "missing"
        print(f"{state}: {config.parent} managed block")
        return 1

    insert = end_of_commands_map(rest, commands_index, entry_indent)
    updated = [*rest[:insert], *block, *rest[insert:]]
    config.write_text("\n".join(updated) + "\n", encoding="utf-8")
    print(f"{'refreshed' if existing else 'installed'}: {config.parent}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
